"use client";
import React,{useState} from "react";
import type {EvidenceSnapshot} from "@/contracts/domain";
import {StatusBadge} from "./StatusBadge";
import {Metric,dateLabel,chainLabel} from "./ForensicUI";
import {displaySafe} from "./display-safety";
export function EvidenceViewer({evidence,explorerUrl}:{evidence:EvidenceSnapshot;explorerUrl?:string|null}) {
 const [copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false),[raw,setRaw]=useState(false);
 async function copy(){try{await navigator.clipboard.writeText(JSON.stringify(displaySafe(evidence),null,2));setCopied(true);setCopyError(false);}catch{setCopyError(true);}}
 const facts=displaySafe(evidence.facts??{}) as Record<string,unknown>;
 return <div className="evidence-card"><div className="section-heading"><h3>证据可追溯档案 (Evidence Audit)</h3><StatusBadge type="provenance" value={evidence.provenance} size="sm"/></div><dl className="evidence-grid"><Metric label="命中规则 / Rule" value={evidence.rule} mono/><Metric label="目标链 / Chain" value={<>{chainLabel(evidence.chainId,evidence.chainName)} <span className="mono">(ID: {evidence.chainId})</span></>}/><Metric label="Observed At" value={dateLabel(evidence.observedAt)} mono/>{evidence.target&&<Metric label="Target" value={evidence.target} mono/>}{evidence.txHash&&<Metric label="Tx Hash" value={<><span className="hash-value mono">{evidence.txHash}</span>{explorerUrl&&/^0x[0-9a-fA-F]{64}$/.test(evidence.txHash)&&<a href={`${explorerUrl.replace(/\/$/,"")}/tx/${evidence.txHash}`} target="_blank" rel="noopener noreferrer">在区块链浏览器中查看 ↗</a>}</>}/>} {evidence.blockNumber&&<Metric label="Block" value={`#${evidence.blockNumber}`} mono/>}{evidence.logIndex!==undefined&&<Metric label="Log Index" value={evidence.logIndex} mono/>}</dl><div className="summary-section"><h3>观测事实 / Observed Facts</h3>{!Object.keys(facts).length?<p className="evidence-caption">No data · 该快照未提供事实字段。</p>:<dl className="evidence-grid">{Object.entries(facts).map(([key,value])=><Metric key={key} label={key} value={typeof value==="object"?JSON.stringify(value):String(value??"—")} mono/>)}</dl>}</div><div className="summary-section"><h3>Evidence Snapshot · IMMUTABLE RECORD</h3><p className="evidence-caption">SHA-256: — · 当前 API 未提供服务端存证哈希；未进行第三方认证。</p></div><div className="page-actions evidence-footer"><button className="button" onClick={copy} aria-label="复制原始证据 JSON">{copied?"✓ 已复制 JSON":"复制原始证据 JSON"}</button><button className="button" aria-expanded={raw} onClick={()=>setRaw(!raw)}>{raw?"收起原始 JSON":"查看原始 JSON"}</button></div>{copyError&&<p role="alert">复制失败，请查看原始 JSON 后手动复制。</p>}{raw&&<pre>{JSON.stringify(displaySafe(evidence),null,2)}</pre>}</div>;
}
